"""initial_migration

Revision ID: 1a72806cee17
Revises: 
Create Date: 2023-09-11 12:03:22.526622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a72806cee17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('reminder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'reminders', ['reminder_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'reminder_id')
    # ### end Alembic commands ###
